FinalEstore/PETSHOP/petshop/models.py
from . import db


class Product(db.Model):
    __tablename__='product'
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(64), unique=True)
    category = db.Column(db.String(64), nullable=False)
    description = db.Column(db.String(500), nullable=False)
    image = db.Column(db.String(60), nullable=False, default = 'defaultcity.jpg')
    price = db.Column(db.Float, nullable=False)

    def __repr__(self):
        str = "Id: {}, Name: {}, Category {}, Description: {}, Image: {}, Price {}\n" 
        str =str.format( self.id, self.name,self.category,self.description,self.image,self.price)
        return str

orderdetails = db.Table('orderdetails', 
    db.Column('order_id', db.Integer,db.ForeignKey('orders.id'), nullable=False),
    db.Column('product_id',db.Integer,db.ForeignKey('product.id'),nullable=False),
    db.PrimaryKeyConstraint('order_id', 'product_id') )

class Order(db.Model):
    __tablename__='orders'
    id = db.Column(db.Integer, primary_key=True)
    status = db.Column(db.Boolean, default=False)
    firstname = db.Column(db.String(64))
    surname = db.Column(db.String(64))
    email = db.Column(db.String(128))
    phone = db.Column(db.String(32))
    totalcost = db.Column(db.Float)
    date = db.Column(db.DateTime)
    products = db.relationship("Product", secondary=orderdetails, backref="orders") 
    
    def get_product_details(self):
        return str(self)

    def __repr__(self):
        str = "id: {}, Status: {}, Firstname: {}, Surname: {}, Email: {}, Phone: {}, Date: {}, Total Cost: {}\n" 
        str =str.format( self.id, self.status,self.firstname,self.surname, self.email, self.phone, self.date, self.totalcost)
        return str
    
    

FinalEstore/PETSHOP/petshop/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import SubmitField, StringField
from wtforms.validators import InputRequired, email

# form used in basket
class CheckoutForm(FlaskForm):
    firstname = StringField("Your first name", validators=[InputRequired()])
    surname = StringField("Your surname", validators=[InputRequired()])
    email = StringField("Your email", validators=[InputRequired(), email()])
    phone = StringField("Your phone number", validators=[InputRequired()])
    submit = SubmitField("[Email order to store]")


FinalEstore/PETSHOP/petshop/__init__.py
#import flask - from the package import class
from flask import Flask, render_template
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy

db=SQLAlchemy()
app=Flask(__name__)

#create a function that creates a web application
# a web server will run this web application
def create_app():
    app.debug=True
    app.secret_key='BetterSecretNeeded123'

#set the app configuration data 
    app.config['SQLALCHEMY_DATABASE_URI']='sqlite:///petshop.sqlite'

    #initialize db with flask app
    db.init_app(app)

    bootstrap = Bootstrap(app)
    
    #importing modules here to avoid circular references, register blueprints of routes
    from . import views
    app.register_blueprint(views.bp)
   
    return app

@app.errorhandler(404) 
# inbuilt function which takes error as parameter 
def not_found(e): 
  return render_template("404.html")

@app.errorhandler(500)
def internal_error(e):
  return render_template("500.html")


FinalEstore/PETSHOP/petshop/views.py
from flask import Blueprint, render_template, url_for, request, session, flash, redirect
from .models import Order, Product
from datetime import datetime
from .forms import CheckoutForm
from . import db


bp = Blueprint('main', __name__)

#Route for each Template page

@bp.route('/database')
def database():
    title = "database"
    products = Product.query.order_by(Product.name)
    return render_template('database.html', title=title, products=products)

@bp.route('/Dog_Apparel', methods=['GET','POST'])
def DogApparel():
    title = "Dog Apparel"
    dogApparel = Product.query.filter(Product.category == "Dog Apparel")
    return render_template('Dog_Apparel.html', title=title, dogApparel = dogApparel)

@bp.route('/Dog_CollarLead')
def DogCollarLead():
    dogCollarLead = Product.query.filter(Product.category == "Dog Collar")
    return render_template('Dog_CollarLead.html', dogCollarLead = dogCollarLead)

@bp.route('/Dog_Food')
def DogFood():
    dogFood = Product.query.filter(Product.category == "Dog Food")
    return render_template('Dog_Food.html', dogFood = dogFood)

@bp.route('/Sale')
def sale():
    sale = Product.query.filter(Product.category == "Dog Food")
    return render_template('sale.html', sale = sale)

@bp.route('/Cat_Food')
def CatFood():
    catFood = Product.query.filter(Product.category == "Cat Food")
    return render_template('Cat_Food.html', catFood = catFood)

@bp.route('/Cat_Apparel')
def CatApparel():
    catApparel = Product.query.filter(Product.category == "Cat Apparel")
    return render_template('Cat_Apparel.html', catApparel = catApparel)

@bp.route('/Cat_Toys')
def CatToys():
    catToys = Product.query.filter(Product.category == "Cat Toys")
    return render_template('Cat_Toys.html', catToys = catToys)

@bp.route('/PetShop')
def PetShop():
    return render_template('PetShop.html')

@bp.route('/')
def Landing():
    return render_template('PetShop.html')


#Cart

@bp.route('/Cart', methods=['POST','GET'])
def order():
    product_id = request.values.get('product_id')

    # retrieve order if there is one
    if 'order_id'in session.keys():
        order = Order.query.get(session['order_id'])
        # order will be None if order_id stale
    else:
        # there is no order
        order = None

    # create new order if needed
    if order is None:
        order = Order(status = False, firstname='', surname='', email='', phone='', totalcost=0, date=datetime.now())
        try:
            db.session.add(order)
            db.session.commit()
            session['order_id'] = order.id
        except:
            print('failed at creating a new order')
            order = None
    
    # calcultate totalprice
    totalprice = 0
    if order is not None:
        for product in order.products:
            totalprice = totalprice + product.price
    
    # are we adding an item?
    if product_id is not None and order is not None:
        product = Product.query.get(product_id)
        if product not in order.products:
            try:
                order.products.append(product)
                db.session.commit()
            except:
                return 'There was an issue adding the item to your basket'
            return redirect(url_for('main.order'))
        else:
            flash('item already in basket')
            return redirect(url_for('main.order'))
    
    return render_template('Cart.html', order = order, totalprice = totalprice)


# Delete specific basket items
@bp.route('/deleteorderitem', methods=['POST'])
def deleteorderitem():
    id = request.form['id']
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
        product_to_delete = Product.query.get(id)
        try:
            order.products.remove(product_to_delete)
            db.session.commit()
            return redirect(url_for('main.Cart'))
        except:
            flash('Problem deleting item from order - try EMPTY BASKET or contact our store.')
            
    return redirect(url_for('main.order'))

# Scrap basket
@bp.route('/deleteorder')
def deleteorder():
    if 'order_id' in session:
        del session['order_id']
        flash('All items deleted')
    return redirect(url_for('main.PetShop'))

# Checkout Form
@bp.route('/checkout/', methods=['POST','GET'])
def checkout():
    form = CheckoutForm() 
    if 'order_id' in session:
        order = Order.query.get_or_404(session['order_id'])
       
        if form.validate_on_submit():
            order.status = True
            order.firstname = form.firstname.data
            order.surname = form.surname.data
            order.email = form.email.data
            order.phone = form.phone.data
            totalcost = 0
            for product in order.products:
                totalcost = totalcost + product.price
            order.totalcost = totalcost
            order.date = datetime.now()
            try:
                db.session.commit()
                del session['order_id']
                flash('Thank you! One of our awesome team members will contact you soon...')
                return redirect(url_for('main.PetShop'))
            except:
                return 'There was an issue completing your order'
    return render_template('checkout.html', form = form)



FinalEstore/PETSHOP/petshop/templates/Cart.html
{% extends 'base.html' %}

{% block main %}
<!-- display contents of user basket -->
<section>  
    <div class="container">
        <div class="row co-12 d-flex mt-2 mb-2">
            <h3>Shopping Basket</h3>
        </div>
       </div>
        <!-- each product on seperate row -->
        {% for Product in order.products %}
            <div class="row shadow-md my-row mb-3">
                <div class="col-sm-10 card">
                    <h5 class="card-header">{{Product.name}}</h5>
                    <div class="card-body">
                        <div class="row">
                            <div class="col-2">
                                <img class="img-thumbnail" src="{{url_for('static', filename='img/'+ Product.image)}}">                               
                            </div>
                            <div class="col-10">
                                <!-- Item Description -->                   
                                <p class="card-text">{{Product.description}}</p>   
                            </div>  
                        </div>                      
                    </div>
                </div>
                <br><br>
                <!-- right column has price and delete button -->
                <div class="col-sm-2">
                    <!-- delete item button -->                       
                        <h6>{{"$%.2f"|format(Product.price)}}</h6>                      
                        <form method="POST" action="{{url_for('main.deleteorderitem')}}">
                            <input type="hidden" id="id" name="id" value="product.id">
                            <input type="submit" value="Delete" class="btn btn-primary mb-3">
                        </form> 
                </div>
            </div>
            </div>
            {% endfor %}
            </section>
    <!-- total price and page controls -->
        <section>
            <div class="row co-12 d-flex">
                <h5 class="card-body"> Price = {{ "$%.2f"|format(totalprice) }} </h5>
                
            </div>
        
            <div class="row co-12 d-flex mt-2 mb-4">
                <a href="PetShop" class="btn btn-primary mr-4">Continue Shopping</a>
                <a href="{{ url_for('main.checkout') }}" class="btn btn-primary mr-4">Checkout</a>
                <a href="{{ url_for('main.deleteorder') }}" class="btn btn-primary">Empty Basket</a>
            </div>
        </section>
    </div>
   
</section>

{% endblock %}




FinalEstore/PETSHOP/petshop/templates/Cat_Apparel.html
{% extends 'base.html' %}
{% block head %}

<body>
<h1>TRENDING FASHIONS</h1>
        </div>
{% for Product in catApparel%}
<div class="card-columns">              
  <div class="card">
  <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
    <div class="card-body" >
      <h4 class="card-title">{{Product.name}}</h4>
      <p class="card-text">{{Product.description}}</p>
    </div>  
<div class="card-footer">{{"$%.2f"|format(Product.price)}}
  <form action="{{ url_for('main.order') }}">
    <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
    <input class="btn btn-primary" type="submit" value="Add to Basket">
</form>
</div>
</div>
                      
</div>
{% endfor %}


</div>
</body>
</section>
                
{% endblock %}

FinalEstore/PETSHOP/petshop/templates/Cat_Food.html
{% extends 'base.html' %}
{% block head %}

<body>
<h1>DELICIOUS AND HEALTHY CAT FOOD!</h1>
</div>
{% for Product in catFood%}
<div class="card-columns">              
  <div class="card">
      <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
      <div class="card-body" >
          <h4 class="card-title">{{Product.name}}</h4>
          <p class="card-text">{{Product.description}}</p>
      </div>
       <div class="card-footer">{{"$%.2f"|format(Product.price)}}
        <form action="{{ url_for('main.order') }}">
          <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
          <input class="btn btn-primary" type="submit" value="Add to Basket">
      </form>
</div>
</div>
      
  </div>
  {% endfor %}

  
</div>
</body>
</section>

{% endblock %}

FinalEstore/PETSHOP/petshop/templates/Cat_Toys.html
{% extends 'base.html' %}
{% block head %}
<body>
    
<h1>ENTERTAINING CAT TOYS!</h1>
</div>
{% for Product in catToys%}
<div class="card-columns">              
  <div class="card">
      <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
      <div class="card-body" >
          <h4 class="card-title">{{Product.name}}</h4>
          <p class="card-text">{{Product.description}}</p>
      </div>
       <div class="card-footer">{{"$%.2f"|format(Product.price)}}
        <form action="{{ url_for('main.order') }}">
          <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
          <input class="btn btn-primary" type="submit" value="Add to Basket">
      </form>
</div>
</div>
      
  </div>
  {% endfor %}

  
</div>
</body>
</section>

{% endblock %}

FinalEstore/PETSHOP/petshop/templates/Dog_Apparel.html
{% extends 'base.html' %}
{% block head %}

          <h1>TRENDING STYLES!</h1>      
          {% endblock %}
          {% block main %}         


            </p> </div>
            {% for Product in dogApparel%}
              <div class="card-columns">              
                <div class="card">
                    <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
                    <div class="card-body" >
                        <h4 class="card-title">{{Product.name}}</h4>
                        <p class="card-text">{{Product.description}}</p>
                    </div>
                     <div class="card-footer">{{"$%.2f"|format(Product.price)}}               
                <form action="{{ url_for('main.order') }}">
                <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
                <input class="btn btn-primary" type="submit" value="Add to Basket">
            </form>
            </div>
        </div>                  
    </div>
    {% endfor %}              
    </div>
    </body>
  </section>

    {% endblock %}

FinalEstore/PETSHOP/petshop/templates/Dog_CollarLead.html
{% extends 'base.html' %}
{% block head %}

<body>
   
    <h1>THE BEST COLLARS & LEADS AVAILABLE!</h1>
    </div>
    {% for Product in dogCollarLead%}
    <div class="card-columns">              
      <div class="card">
          <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
          <div class="card-body" >
              <h4 class="card-title">{{Product.name}}</h4>
              <p class="card-text">{{Product.description}}</p>
          </div>
           <div class="card-footer">{{"$%.2f"|format(Product.price)}}
            <form action="{{ url_for('main.order') }}">
              <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
              <input class="btn btn-primary" type="submit" value="Add to Basket">
          </form>
  </div>
</div>
          
      </div>
      {% endfor %}

      
</div>
</body>
</section>

{% endblock %}


FinalEstore/PETSHOP/petshop/templates/Dog_Food.html
{% extends 'base.html' %}
{% block head %}
<section>
<h1>ONLY THE BEST DOG FOOD!</h1>
</div>
{% for Product in dogFood%}
<div class="card-columns">              
  <div class="card">
      <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
      <div class="card-body" >
          <h4 class="card-title">{{Product.name}}</h4>
          <p class="card-text">{{Product.description}}</p>
      </div>
       <div class="card-footer">{{"$%.2f"|format(Product.price)}}
        <form action="{{ url_for('main.order') }}">
          <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
          <input class="btn btn-primary" type="submit" value="Add to Basket">
      </form>
</div>
</div>
      
  </div>
  {% endfor %}

  
</div>
</body>
</section>

{% endblock %}

FinalEstore/PETSHOP/petshop/templates/PetShop.html
{% extends 'base.html' %}
{% block head %}

{% endblock %}
{% block main %}


<section>
    <body>
        <div class="Highlighted" style=text-align:center>
    
        <a href="Dog_Food">
        <img src=https://image.budgetpetproducts.com.au/products_pictures/1/95/94892.jpg class="center-block img-responsive" >
        </a>
        <a href="Dog_CollarLead">
        <img src=https://image.budgetpetproducts.com.au/products_pictures/1/95/94886.jpg class="center-block img-responsive" >
        </a>
        <a href="Dog_Apparel">
        <img src=https://image.budgetpetproducts.com.au/products_pictures/1/95/94895.jpg class="center-block img-responsive" >
        </a>
        
        </div>
        <div style=text-align:center>
        <p>
          <h1>Some of our biggest sales ever! 
          </h1> 
        
          <a href="Sale">
            <img src=https://182c095af351c4f86c03-3dcc1a0c5ec1b04fc3bac90ca50c8ee4.ssl.cf4.rackcdn.com/products_pictures/2021/11/17/110355.gif
             class="img-responsive" width="500" height="500">
            </a>
        </p>
        </div>
        <div style=text-align:center>
          <p>
            <a href="Cat_Food">
            <img src=https://image.budgetpetproducts.com.au/products_pictures/1/95/94861.jpg class="">
            </a>
            <a href="Cat_Toys">
            <img src=https://image.budgetpetproducts.com.au/products_pictures/1/95/94860.jpg>
            </a>
            <a href="Cat_Apparel">
            <img src=https://image.budgetpetproducts.com.au/products_pictures/1/95/94868.jpg>
            </a>
          </p>
      </div>
      
      </body>
  
    </section>
    
    
    <footer>
        <div>
          <p>
            <h3>Email: T&Sommerfeld@petshop.com
              </h3>
            </p>
            <img src=https://www.budgetpetproducts.com.au/images/awards/canstar.svg height=50% width = 50%>
            
        </div>
    </footer>
    
    {% endblock %}

FinalEstore/PETSHOP/petshop/templates/base.html
<!DOCTYPE html>
<html lang="en">
<section>

<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <meta charset="utf-8">
    
    <meta name="description" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>T's Pet Shop</title>
    <style>
       .my-row { border: 1px solid grey}
        h1 {font-family:cursive}
        h1 {font-size: 200%}
        h2 {font-family:monospace}
        h2 {border:lawngreen}
        h3 {font-family:'Courier New', Courier, monospace}
        
            button{padding: 0}
            button{border:gray}
        
    </style>
</head>
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

<!-- Store Name -->
<header>
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container">


        <a class="navbar-brand" href="/PetShop">T's Pet Shop</a>


        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="true" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

      <!-- NavBar -->
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/PetShop">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="/Sale">Sale Items</a>
            </li>

            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                Dog Products
              </a>
              <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                <a class="dropdown-item" href="/Dog_Apparel">Apparel</a>
                <a class="dropdown-item" href="/Dog_CollarLead">Collar & Leads</a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="/Dog_Food">Dog Food</a>
              </div>             
            </li>

            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                  Cat Products
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item" href="/Cat_Apparel">Apparel</a>
                  <a class="dropdown-item" href="/Cat_Toys">Toys</a>
                  <div class="dropdown-divider"></div>
                  <a class="dropdown-item" href="/Cat_Food">Cat Food</a>
                </div>
                
              </li>

            <li class="nav-item active">
              <a class="nav-link" href="/Cart">Shopping Cart</a>
            </li>
          </ul>

          <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            
          </form>
        </div>
     </div>
 </nav>
 <div class="Highlighted" style=text-align:center>
    <img src="https://182c095af351c4f86c03-3dcc1a0c5ec1b04fc3bac90ca50c8ee4.ssl.cf4.rackcdn.com/products_pictures/2021/11/11/109555.gif" width="100%" height="200">
    {% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class ="card" class=flash >
    {% for message in messages %}
      <h1>{{ message }}</h1>
    {% endfor %}
    </div>
  {% endif %}
{% endwith %}
{% block body %}{% endblock %}

 {% block head %}{% endblock %}
 </div>
 
</header>

</section>

<div class="container-fluid">
    <main>
        {% block main %}{% endblock %}
    </main>
</div>

FinalEstore/PETSHOP/petshop/templates/checkout.html
{% extends 'base.html' %}
{% block head %}

{% endblock %}

{% block main %}
{% import "bootstrap/wtf.html" as wtf %}
    <section>  
        <div class="container">
            <div class="row">
                
                <div class = "col-12">
                    <h1>Checkout </h1>
                    <p>
                        Thank you for your interest. Please provide your details so that someone from our sales team can contact you to finalise details and take payment. Thank you! 
                    </p>
                </div>
            </div>
            <div class="row">
                <div class = "col-6">
                    {{wtf.quick_form(form)}}
                </div>
                {% with messages = get_flashed_messages() %}
                
  {% if messages %}
    
    {% for message in messages %}
      <h1>{{ message }}</h1>
    {% endfor %}
    </div>
    
  {% endif %}
  
{% endwith %}

{% block body %}{% endblock %}
<footer>
            </div>
        </div>
    </section>
    <div>
        <a href="/Cart" class="btn btn-primary mr-sm-2">Return to Cart</a>
        <a href="/PetShop" class="btn btn-primary mr-4">Continue Shopping</a>
    
        </div>
    </footer>
{% endblock %}

FinalEstore/PETSHOP/petshop/templates/sale.html
{% extends 'base.html' %}
{% block head %}
<body>

<h1>SALE ITEMS - UP TO 60% OFF!</h1>
</div>
{% for Product in sale%}
<div class="card-columns">              
  <div class="card">
      <img class="card-img-top" src="{{url_for('static', filename='img/'+Product.image)}}" alt="Card image" width="100%" height="100%" >
      <div class="card-body" >
          <h4 class="card-title">{{Product.name}}</h4>
          <p class="card-text">{{Product.description}}</p>
      </div>
       <div class="card-footer">{{"$%.2f"|format(Product.price)}}
        <form action="{{ url_for('main.order') }}">
          <input type="hidden" id="product_id" name="product_id" value="{{ Product.id }}">
          <input class="btn btn-primary" type="submit" value="Add to Basket">
      </form>
</div>
</div>
      
  </div>
  {% endfor %}

  
</div>
</body>
</section>

{% endblock %}